## Redis Service
services:
    redis:
        image: "redis:latest"
        container_name: "redis-actuator-demo"
        ports:
        - "6379:6379"
        networks:
        - actuator-demo-network
networks:
    actuator-demo-network:
        driver: bridge
