spring:
  application:
    name: actuator-demo2

# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"
  # endpoint:
  #   health:
  #     show-details: always
  #   env:
  #     show-values: always