spring:
  main:
    banner-mode: "off"
  application:
    name: actuator-demo2
  lifecycle:
    timeout-per-shutdown-phase: 30s
  # security:
  #   user:
  #     name: admin
  #     password: 123456 ## only for demo, do not use in production

server:
  port: 8080

management:
  info:
    build:
      enabled: true
    git:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true
    java:
      enabled: true
    ssl:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
  #   shutdown:
  #     access: unrestricted
  #   heapdump:
  #     access: unrestricted
    health:
      show-details: always
      status:
# https://docs.spring.io/spring-boot/api/java/org/springframework/boot/actuate/health/Status.html
        order: down, out-of-service, unknown, up
        http-mapping:
          down: 503
          out-of-service: 503
          unknown: 500
          up: 200
      cache:
        time-to-live: 15s
      probes:
        enabled: true
        # make the liveness group available at /livez
        # and the readiness group available at /readyz on the main server port.
        add-additional-paths: true
      group:
        liveness:
          include: livenessState, diskSpace
        readiness:
          include: readinessState, redis
    info:
      cache:
        time-to-live: 1h
    env:
      show-values: always
  server:
    port: 8081
